name: 16 - Working with Environments
run-name: 16 - Working with Environments | Env - ${{ inputs.target-env }}
on:
  workflow_dispatch:
    inputs:
      target-env:
        type: environment
        default: staging
jobs:
  echo:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-env }}
    env:
      my_env_value: ${{ vars.MY_ENV_VALUE || 'default_value' }}
    steps:
      - name: Echo Vars
        run: echo "Env variable ${{ env.my_env_value }}"
