name: "CI/CD Deployment"

on:
  push:
    branches:
      - develop
      - staging
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    environment: develop
    env:
      server_host: ${{ vars.SERVER_HOST }}
    steps:
      - name: Checkout Code
        run: echo "Environment ${{ env.server_host }}"
  deploy-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production
    env:
      server_host: ${{ vars.SERVER_HOST }}
    steps:
      - name: Checkout Code
        run: echo "Environment ${{ env.server_host }}"
